// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNi2pUyKq2-K3nBKQE9mRmidT8PRrOq1w',
    appId: '1:712894584402:web:24b9a0aa1dc4600b89318b',
    messagingSenderId: '712894584402',
    projectId: 'sgproj-94193',
    authDomain: 'sgproj-94193.firebaseapp.com',
    storageBucket: 'sgproj-94193.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdDRGUm0nXxoe9iH4XGuGXfaEi9c3A34A',
    appId: '1:712894584402:android:65f94bb827f42e8789318b',
    messagingSenderId: '712894584402',
    projectId: 'sgproj-94193',
    storageBucket: 'sgproj-94193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0WmN6NcGphl3TMUsSPwps5_etQHf_mG4',
    appId: '1:712894584402:ios:a70e12aa4a2820ab89318b',
    messagingSenderId: '712894584402',
    projectId: 'sgproj-94193',
    storageBucket: 'sgproj-94193.appspot.com',
    iosBundleId: 'com.example.project1',
  );

}